;; (define (abs x) 
;;   (cond ((< x 0) (- x))
;;         ((= x 0) 0)
;;         ((> x 0) x)))
;; (abs -5)

;; (define (abs x)
;;         (cond ((< x 0) (- x))
;;         (else x)))
;; (abs -10)

;; (define (abs x) 
;;   (if (< x 0) 
;;       (- x) 
;;       x))
;; (abs -20)

(define (>= x y) (or (> x y) (= x y)))
(>= 10 5)
(>= 5 10)